import { useEffect, useRef, useState } from "react";
import { apiUrl, errorMessage, postJson, requestError } from "../api";
import { CustomSelect, FixedTableCard, Section, Badge, TruncatedText } from "../components/Primitives";
import { ScrollablePagedTable, usePagedCandidates } from "../components/ScrollablePagedTable";
import { Drawer } from "../components/Dialog";

export function BusinessImportPanel({ items, onCreated, profiles = {}, onDetail, initialProfile = "mini", currentQuestionIds = [], coveragePlan, corpusFingerprint }: { items: any[]; onCreated: () => Promise<void>; profiles?: Record<string, any>; onDetail?: (row: any) => void; initialProfile?: string; currentQuestionIds?: string[]; coveragePlan?: any; corpusFingerprint?: unknown }) {
  const quotas = Object.fromEntries(Object.entries(profiles).map(([name, counts]) => [name, [counts.positive_count, counts.ablation_count, counts.negative_count]]));
  const [file, setFile] = useState<File | null>(null), [preview, setPreview] = useState<any>(null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [selected, setSelected] = useState<string[]>([]), [profile, setProfile] = useState(initialProfile), [source, setSource] = useState("all"), [group, setGroup] = useState("all");
  const [assembling, setAssembling] = useState(false), [quality, setQuality] = useState("all");
  const target = quotas[profile] || [];
  const selectedRows = useRef(new Map<string, any>());
  const [query, setQuery] = useState("");
  const [importOpen, setImportOpen] = useState(false), [matching, setMatching] = useState<any>(null), [checking, setChecking] = useState(false), [detail, setDetail] = useState<any>(null);
  const request = useRef(0);
  const plan = matching?.coverage_plan || (coveragePlan?.profile?.name === profile ? coveragePlan : null);
  const identity = JSON.stringify([corpusFingerprint, initialProfile, currentQuestionIds[0], profile]);
  const path = `/api/governance/candidates?source=${source}&group=${group}&status=${quality}&search=${encodeURIComponent(query)}`;
  const pageData = usePagedCandidates(identity, path);
  const syncing = pageData.loading, pool: any[] = pageData.rows;
  const summary = pageData?.summary;
  const counts = ["positive", "ablation", "negative"].map(category => [...selectedRows.current.values()].filter(row => selected.includes(row.id) && row.test_category === category).length);

  const exact = target.length === 3 && counts.every((count, index) => count === target[index]);
  useEffect(() => {
    const ticket = ++request.current; setMatching(null); setError("");
    if (!selected.length) { setChecking(false); return; }
    setChecking(true);
    void postJson("/api/governance/generation-runs/from-pool/preview", { profile, question_ids: selected }).then(result => { if (ticket === request.current) setMatching(result); }).catch(reason => { if (ticket === request.current) setError(errorMessage(reason)); }).finally(() => { if (ticket === request.current) setChecking(false); });
    return () => { request.current++; };
  }, [profile, selected]);
  const upload = async (confirm = false) => { if (!file) return; setBusy(true); setError(""); try { const response = await fetch(apiUrl(`/api/governance/imports?filename=${encodeURIComponent(file.name)}&confirm=${confirm}`), { method: "POST", headers: { "Content-Type": "application/octet-stream" }, body: file }); const result = await response.json(); if (!response.ok) throw new Error(requestError(result.detail, response.status)); setPreview(result); if (confirm) { await onCreated(); setFile(null); } } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const create = async () => { if (!matching?.valid) return; setBusy(true); setError(""); try { await postJson("/api/governance/generation-runs/from-pool", { profile, question_ids: selected, plan_id: matching.plan_id }); setSelected([]); setAssembling(false); selectedRows.current.clear(); await onCreated(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  return <><Section title={assembling ? "组建 Golden" : "候选池"}>
    {(error || pageData.error) && <p className="error-notice" role="alert">{error || pageData.error}</p>}
    <div className="pool-summary-strip">候选 {summary?.total ?? "—"} · 可用 {summary?.machine_qualified ?? "—"} · 待治理 {summary ? summary.needs_processing + summary.pending_checks : "—"}{syncing && <small>正在同步…</small>}</div>
    <div className="candidate-pool-toolbar">{assembling && <span className="pool-profile-selector"><CustomSelect ariaLabel="候选池 Profile" value={profile} onChange={setProfile} options={Object.keys(quotas).map(value => ({ value, label: `${value.toUpperCase()} · ${quotas[value].reduce((sum: number, count: number) => sum + count, 0)}题（${quotas[value].join(" / ")}）` }))} /></span>}<CustomSelect ariaLabel="候选来源" value={source} onChange={setSource} options={[{ value: "all", label: "全部来源" }, { value: "ai_generated", label: "AI 生成" }, { value: "business_import", label: "业务导入" }]} /><CustomSelect ariaLabel="Evaluation Group" value={group} onChange={setGroup} options={["all", "positive", "ablation", "negative"].map(value => ({ value, label: value === "all" ? "全部评测组" : value }))} /><CustomSelect ariaLabel="候选质量" value={quality} onChange={setQuality} options={[{value:"all",label:"全部质量"},{value:"usable",label:"可用"},{value:"govern",label:"待治理"}]} /><input aria-label="搜索候选题" type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索候选题" /><button className="secondary" disabled={busy} onClick={() => setImportOpen(true)}>导入业务用例</button>{assembling ? <><button className="secondary" onClick={() => { setAssembling(false); setSelected([]); selectedRows.current.clear(); setMatching(null); }}>返回浏览</button><button className="primary" disabled={busy || checking || !exact || !matching?.valid} onClick={() => void create()}>创建待审核测试集</button></> : <button className="primary" onClick={() => setAssembling(true)}>创建 Golden</button>}</div>
    {assembling && <div className="pool-profile-match"><strong>{profile.toUpperCase()} · 已选 {selected.length} / {target.reduce((sum: number, count: number) => sum + count, 0)}</strong><span>{["P", "A", "N"].map((label, index) => `${label} ${counts[index]}/${target[index] ?? "—"}`).join(" · ")}</span><span>Topics {plan?.clusters?.filter((topic: any) => plan.slots.some((slot: any) => slot.topic_cluster === topic.cluster_id && matching?.matching?.[slot.slot_id])).length ?? 0}/{plan?.final_k ?? "待规划"}</span>{plan && <CoverageSummary run={{ artifacts:{ hard_validation:{ frozen_plan:plan } } }} questions={selected.map(id => selectedRows.current.get(id)).filter(Boolean)} documents={[]} />}</div>}
    {assembling && matching?.gaps?.length > 0 && <details><summary>查看 Coverage 缺口 · {matching.gaps.length}</summary><FixedTableCard><table><thead><tr><th>Slot</th><th>Topic</th><th>Group / Construction</th><th>缺口</th></tr></thead><tbody>{matching.gaps.map((gap: any) => <tr key={gap.slot_id}><td>{gap.slot_id}</td><td>{gap.topic_cluster}</td><td>{gap.evaluation_group} / {gap.construction_type}</td><td>{gap.deficit}</td></tr>)}</tbody></table></FixedTableCard></details>}
    <ScrollablePagedTable className="fixed-table" resetKey={identity + path} loading={pageData.loading} hasMore={pageData.hasMore} onMore={pageData.loadMore}><table className="candidate-pool-table"><colgroup>{[...(assembling ? [38] : []), 0, 100, 95, 95, 90].map((width,index)=><col key={index} style={width ? {width} : undefined} />)}</colgroup><thead><tr>{assembling && <th>选择</th>}<th>问题</th><th>评测组</th><th>来源</th><th>质量状态</th><th>操作</th></tr></thead><tbody>{pool.map(row => <tr key={row.id} data-question-id={row.id}>{assembling && <td><input aria-label={`选择 ${row.question}`} type="checkbox" checked={selected.includes(row.id)} onChange={event => { selectedRows.current.set(row.id,row); setSelected(ids => event.target.checked ? [...ids,row.id] : ids.filter(id=>id!==row.id)); }} /></td>}<td><TruncatedText lines={2}>{row.question}</TruncatedText></td><td>{row.test_category}</td><td>{row.raw?.source === "business_import" ? "业务导入" : "AI 生成"}</td><td><Badge tone={row.qualification_status === "machine_qualified" || row.qualification_status === "human_approved" ? "good" : "warning"}>{row.qualification_status === "machine_qualified" ? "机器合格" : row.qualification_status === "human_approved" ? "人工通过" : "待治理"}</Badge></td><td><button className="text-button" onClick={() => onDetail ? onDetail(row) : setDetail(row)}>查看详情</button></td></tr>)}</tbody></table></ScrollablePagedTable>
  </Section>
  <Drawer showCloseFooter={false} open={importOpen} onOpenChange={setImportOpen} title="导入业务用例"><div className="drawer-body"><p>CSV / XLSX · 先预览，再确认。存在错误时整批阻断。</p><div className="header-actions"><a className="secondary" href={apiUrl("/api/governance/import-template?format=csv")} download>下载 CSV 模板</a><a className="secondary" href={apiUrl("/api/governance/import-template?format=xlsx")} download>下载 XLSX 模板</a><input aria-label="业务测试集文件" type="file" accept=".csv,.xlsx" disabled={busy} onChange={event => { setFile(event.target.files?.[0] || null); setPreview(null); }} /><button className="secondary" disabled={!file || busy} onClick={() => void upload()}>预览导入</button><button className="primary" disabled={!file || busy || !preview?.valid_count || !!preview?.error_count} onClick={() => void upload(true)}>确认导入 {preview?.valid_count || 0} 题</button></div><p>Evaluation Group：positive / ablation / negative；Question Type：Fact / Aggregation / Bridge 或留空。正向与消融需填写真实原文 Evidence / Document；Negative 填写 Expected Behavior / Negative Subtype，答案与证据可留空。</p>{error && <p className="error-notice" role="alert">{error}</p>}{preview && <><p>有效 {preview.valid_count} · 错误 {preview.error_count}{!file && " · 已确认导入"}</p><FixedTableCard><table><thead><tr><th>行</th><th>问题</th><th>逐行结果</th></tr></thead><tbody>{preview.rows?.map((row: any) => <tr key={row.row}><td>{row.row}</td><td>{row.fields.Question}</td><td>{row.errors.length ? row.errors.join("；") : "有效"}</td></tr>)}</tbody></table></FixedTableCard></>}</div></Drawer>
  <Drawer showCloseFooter={false} open={!!detail} onOpenChange={open => !open && setDetail(null)} title="候选池题目详情"><div className="drawer-body"><h3>{detail?.question}</h3><p>{detail?.reference_answer || detail?.expected_behavior || "未记录"}</p></div></Drawer></>;
}

export function CoverageSummary({ run, questions, documents, persistedPlan }: { run: any; questions: any[]; documents: any[]; persistedPlan?: any }) {
  const [open, setOpen] = useState(false);
  const plan = run?.artifacts?.hard_validation?.frozen_plan;
  const displayPlan = plan?.plan_id && plan.plan_id === persistedPlan?.plan_id ? { ...plan, clusters: plan.clusters.map((cluster: any) => ({ ...cluster, semantic_label: persistedPlan.clusters.find((item: any) => item.cluster_id === cluster.cluster_id)?.semantic_label || cluster.semantic_label })) } : plan;
  const slots = plan?.slots || run?.artifacts?.coverage_plan || [];
  return <div className="coverage-summary"><span><strong>Coverage</strong> · {plan?.planner_version ? `${plan.clusters?.length ?? "未采集"} Topics · ${slots.length} Slots · Gap ${slots.filter((slot: any) => !questions.some(row => (row.slot || row.raw?.coverage_slot) === (slot.slot_id || slot.slot))).length} · Merge ${plan.merge_mapping?.length ?? 0}` : "Legacy · 原始 Slot 审计"}</span><button className="text-button" onClick={() => setOpen(true)}>查看 Coverage</button>
    <Drawer showCloseFooter={false} open={open} onOpenChange={setOpen} title="Coverage 规划与 Slot 审计" className="search-space-drawer"><CoveragePlanDetails plan={displayPlan} slots={slots} documents={documents} attempts={run?.artifacts?.slot_audit} gap={slots.filter((slot: any) => !questions.some(row => (row.slot || row.raw?.coverage_slot) === (slot.slot_id || slot.slot))).length} /></Drawer>
  </div>;
}

export function CurrentCoveragePreview({ profile, corpusFingerprint, documents }: { profile: string; corpusFingerprint?: unknown; documents: any[] }) {
  const [preview, setPreview] = useState<any>(null), [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const source = JSON.stringify([profile, corpusFingerprint ?? documents.map(doc => [doc.id, doc.source_fingerprint])]);
  const request = useRef(0), currentSource = useRef(source); currentSource.current = source;
  useEffect(() => { request.current++; setPreview(null); setBusy(false); setError(""); setOpen(false); return () => { request.current++; }; }, [source]);
  const runPreview = async () => {
    const ticket = ++request.current, captured = source;
    setBusy(true); setPreview(null); setError("");
    try {
      const result: any = await postJson("/api/governance/coverage-preview", { profile });
      if (ticket !== request.current || captured !== currentSource.current) return;
      if (result.profile?.name !== profile || corpusFingerprint != null && JSON.stringify(result.corpus_fingerprint) !== JSON.stringify(corpusFingerprint)) throw new Error("Preview 已过期：Profile 或 Corpus 已变化，请刷新后重新预览");
      setPreview(result); setOpen(true);
    } catch (reason) { if (ticket === request.current && captured === currentSource.current) setError(errorMessage(reason)); }
    finally { if (ticket === request.current && captured === currentSource.current) setBusy(false); }
  };
  return <div className="current-coverage-preview"><div className="coverage-preview-line"><span><strong>当前 Corpus · V2 Planner Preview</strong> · {documents.length} 文档 · {profile.toUpperCase()} · {preview ? `${preview.slots?.length || 0} Slots${preview.gaps ? ` · ${preview.gaps.length} 缺口` : ""}` : busy ? "正在规划" : "尚无当前 Preview"}</span><div className="header-actions"><button className="secondary" disabled={busy} onClick={() => void runPreview()}>{busy ? "正在 Preview…" : "预览当前 Corpus Coverage"}</button>{preview && <button className="text-button" onClick={() => setOpen(true)}>查看当前 Preview</button>}</div></div>
    <small className="muted">手动 Preview 仅规划材料与配额，不生成题目；Profile 或 Corpus 改变后须重新预览。</small>
    {error && <p className="error-notice" role="alert">Preview 失败：{error}</p>}
    <Drawer showCloseFooter={false} open={open} onOpenChange={setOpen} title="当前 Corpus · V2 Coverage Preview" className="search-space-drawer"><CoveragePlanDetails plan={preview} slots={preview?.slots || []} documents={documents} /></Drawer>
  </div>;
}

function CoveragePlanDetails({ plan, slots, documents, attempts, gap = plan?.gaps?.length ?? 0 }: { plan: any; slots: any[]; documents: any[]; attempts?: unknown; gap?: number }) {
  return <div className="drawer-body"><div className="coverage-drawer-summary"><strong>{plan?.clusters?.length ?? 0} Topics · {slots.length} Slots · Gap {gap} · Merge {plan?.merge_mapping?.length ?? 0}</strong><details className="export-menu"><summary aria-label="Coverage 更多操作">⋯</summary><div><details><summary>技术审计</summary><p>Planner {plan?.planner_version || "Legacy / 未采集"} · Profile {plan?.profile?.name || "未采集"}</p><p>N {Object.keys(plan?.chunk_clusters || {}).length} · Initial K {plan?.initial_k ?? "未采集"} · Final K {plan?.final_k ?? "未采集"}</p><p>复用 Slots {plan?.reuse_statistics?.reused_slots ?? "未采集"}</p><p>Merge {plan?.merge_mapping?.length ? plan.merge_mapping.map((item: any) => `${item.from} → ${item.to}（${item.size} Child）`).join("；") : "0"}</p></details></div></details></div>
    <div className="coverage-topic-list">{(plan?.clusters || []).map((cluster: any) => {
      const topicSlots = slots.filter((slot: any) => slot.topic_cluster === cluster.cluster_id);
      return <details key={cluster.cluster_id}><summary><strong>{cluster.cluster_id} · {cluster.semantic_label || cluster.label}</strong><span>{cluster.size} Child · {topicSlots.length} Slots</span><span>P {cluster.quotas?.positive ?? topicSlots.filter((slot: any) => (slot.evaluation_group || slot.test_category) === "positive").length} · A {cluster.quotas?.ablation ?? topicSlots.filter((slot: any) => (slot.evaluation_group || slot.test_category) === "ablation").length} · N {cluster.quotas?.negative ?? topicSlots.filter((slot: any) => (slot.evaluation_group || slot.test_category) === "negative").length}</span><small>主要来源：{[...new Set(topicSlots.map((slot: any) => documents.find(doc => doc.id === slot.document_id)?.name || slot.document_name).filter(Boolean))].join("、") || "来源详情见 Slot"}</small></summary><p>构造分布：{[...new Set(topicSlots.map((slot: any) => slot.construction_type))].map(type => `${type || "未记录"} ${topicSlots.filter((slot: any) => slot.construction_type === type).length}`).join(" · ")}</p><FixedTableCard><table><thead><tr><th>Slot</th><th>Group / Construction</th><th>Evidence</th></tr></thead><tbody>{topicSlots.map((slot: any) => <tr key={slot.slot_id || slot.slot}><td>{slot.slot_id || slot.slot}</td><td>{slot.evaluation_group || slot.test_category} · {slot.construction_type}</td><td>{documents.find(doc => doc.id === slot.document_id)?.name || slot.document_id} · {slot.section_path} · {slot.material_chunk_ids?.join("、")}</td></tr>)}</tbody></table></FixedTableCard></details>;
    })}</div>
    <details><summary>Slot / 材料来源 / 章节</summary><FixedTableCard><table><thead><tr><th>Slot</th><th>Group / Topic</th><th>材料 / 章节</th><th>抽样 / 复用</th></tr></thead><tbody>{slots.map((slot: any, index: number) => <tr key={slot.slot_id || slot.slot || index}><td>{slot.slot_id || slot.slot}</td><td>{slot.evaluation_group || slot.test_category} / {slot.topic_cluster ?? "未记录"}</td><td>{documents.find(doc => doc.id === slot.document_id)?.name || slot.document_id || "未记录"} / {slot.section_path || "未记录"} · {slot.material_chunk_ids?.join("、")}</td><td>{slot.selected_reason || slot.sampling_priority || "未记录"} · {slot.reused == null ? "未采集" : slot.reused ? "复用" : "未使用材料"}</td></tr>)}</tbody></table></FixedTableCard></details>
  </div>;
}
