import { useEffect, useState } from "react";
import { ArrowRight, Play } from "lucide-react";
import { getJson, postJson, errorMessage } from "../api";
import { Badge, Metric, Section } from "../components/Primitives";

export function EvaluationPage({ data, navigate }: { data: any; navigate: (page: any) => void }) {
  const [run, setRun] = useState<any>(data.evaluation); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!run?.id || !["running", "queued"].includes(run.status)) return; const timer = window.setTimeout(() => { getJson<any>(`/api/evaluations/${run.id}`).then(setRun).catch(reason => setError(errorMessage(reason))); }, 800); return () => window.clearTimeout(timer); }, [run]);
  const start = async () => { setBusy(true); setError(""); try { setRun(await postJson("/api/evaluations/run")); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const result = run?.result || {}; const cases = run?.cases || [];
  const gates = result.gates || {}; const comparison = result.comparison_metrics || {};
  return <div className="page"><div className="page-title"><div><h1>评测</h1><p>仅评测已批准 Golden Dataset Snapshot；11 项 Gate 由后端计算。</p></div><div className="header-actions"><button className="secondary" onClick={() => void start()} disabled={busy || run?.status === "running"}><Play size={15} />{busy || run?.status === "running" ? "评测进行中" : "运行 Baseline Evaluation"}</button><button className="primary" onClick={() => navigate("evolution")}>进入进化实验室 <ArrowRight size={15} /></button></div></div>{error && <p className="error-notice" role="alert">{error}</p>}<div className="metrics-grid four"><Metric label="状态" value={run?.status || "Not Run"} /><Metric label="Overall" value={result.overall_score ?? "Not Evaluable"} note="仅展示，不替代 Gate" /><Metric label="Hard Gate" value={gates.total ? `${gates.passed_count} / ${gates.total}` : "Not Run"} /><Metric label="TTFT" value={comparison.ttft_seconds == null ? "Not Measured" : `${comparison.ttft_seconds}s`} /></div><Section title="评测报告" action={<Badge tone={gates.passed ? "good" : "warning"}>{gates.passed ? "11 / 11 PASS" : result.overall_score_status || "Not Run"}</Badge>}><dl><dt>Dataset Snapshot</dt><dd>{run?.dataset_version_id || "Not Run"}</dd><dt>Gate</dt><dd>{gates.total ? `${gates.passed_count} / ${gates.total} PASS` : "Not Run"}</dd><dt>Token Cost</dt><dd>{comparison.token_cost ?? "Not Measured"}</dd><dt>Retrieval</dt><dd>Recall {comparison.recall_at_k ?? "—"} · Precision {comparison.precision_at_k ?? "—"} · MRR {comparison.mrr ?? "—"}</dd></dl></Section><Section title="11 Hard Gates"><div className="table-scroll"><table><thead><tr><th>指标</th><th>实际</th><th>门槛</th><th>状态</th></tr></thead><tbody>{(gates.gates || []).map((gate: any) => <tr key={gate.metric}><td>{gate.metric}</td><td>{gate.actual ?? "—"}</td><td>{gate.operator} {gate.threshold}</td><td>{gate.status}</td></tr>)}{!gates.gates?.length && <tr><td colSpan={4} className="empty-state">暂无正式 Gate 结果。</td></tr>}</tbody></table></div></Section><Section title="单题结果"><div className="table-scroll"><table><thead><tr><th>问题</th><th>组别</th><th>评分</th><th>检索命中</th><th>红线</th></tr></thead><tbody>{cases.map((item: any) => <tr key={item.question_id}><td>{item.question}</td><td>{item.test_category}</td><td>{item.overall_score}</td><td>{String(item.programmatic_metrics?.retrieval_hit ?? "—")}</td><td>{item.redline_pass ? "Passed" : "Failed"}</td></tr>)}{!cases.length && <tr><td colSpan={5} className="empty-state">暂无真实单题结果。</td></tr>}</tbody></table></div></Section></div>;
}
