import { useState } from "react";
import { ArrowRight, Filter } from "lucide-react";
import { Drawer } from "../components/Dialog";
import { Badge, Metric, Section, Status } from "../components/Primitives";

export function EvaluationPage({ data, navigate }: { data: any; navigate: (page: any) => void }) {
  const [filter, setFilter] = useState("All"); const [selected, setSelected] = useState<any>(null); const evaluation = data.evaluation;
  const visible = data.badCases.filter((item: any) => filter === "All" || item.failure_type.includes(filter));
  return <div className="page"><div className="page-title"><div><div className="eyebrow">Baseline Evaluation · Run #{evaluation.id}</div><h1>Evaluation Report</h1><p>{evaluation.config} · {evaluation.dataset} · {evaluation.questions} questions · <Status value={evaluation.status} /></p></div><button className="primary" onClick={() => navigate("evolution")}>Optimize This Run <ArrowRight size={16} /></button></div>
    <div className="metric-groups"><MetricGroup title="Answer Quality" rows={[["Correctness", "78%"], ["Faithfulness", "91%"], ["Completeness", "74%"]]} /><MetricGroup title="Retrieval" rows={[["Recall@K", "82%"], ["MRR", "0.76"]]} /><MetricGroup title="Safety" rows={[["Safety Pass", "96%"]]} /><MetricGroup title="Performance" rows={[["P50 Latency", "1.8s"], ["P95 Latency", "3.6s"], ["Cost", "¥0.021 / query"]]} /></div>
    <div className="two-column"><Section title="SLA Status"><div className="sla-list">{evaluation.sla.map((row: any) => <div key={row.label}><span>{row.label}</span><strong>{row.actual} <small>/ {row.target}</small></strong><Status value={row.status} /></div>)}</div></Section><Section title="Evaluation Coverage"><Metric label="Golden Dataset" value="40 / 40" note="Complete" /><p className="muted">The baseline is evaluated against the complete Golden Dataset, not only selected bad cases.</p></Section></div>
    <Section title="8 Bad Cases" action={<div className="filters"><Filter size={14} />{["All", "Retrieval", "Generation", "Safety", "Latency"].map(name => <button key={name} className={filter === name ? "selected" : ""} onClick={() => setFilter(name)}>{name}</button>)}</div>}><table><thead><tr><th>Case ID</th><th>Question</th><th>Failure Type</th><th>Score</th><th>Severity</th><th>Status</th></tr></thead><tbody>{visible.map((item: any) => <tr key={item.id} onClick={() => setSelected(item)}><td>{item.id}</td><td>{item.question}</td><td>{item.failure_type}</td><td>{item.score}</td><td><Badge tone={item.severity === "High" ? "bad" : "warning"}>{item.severity}</Badge></td><td><Status value={item.status} /></td></tr>)}</tbody></table></Section>
    <Drawer open={!!selected} onOpenChange={() => setSelected(null)} title={selected?.id || "Bad Case"}>{selected && <div className="drawer-body"><Badge tone="bad">{selected.failure_type}</Badge><h3>{selected.question}</h3><h4>Baseline Answer</h4><p>{selected.baseline_answer || "The retrieval trace did not contain enough evidence."}</p><h4>Expected Answer</h4><p>{selected.expected_answer || "Expected response is retained in the Golden Dataset."}</p><h4>Retrieval Trace</h4>{(selected.trace || []).map((trace: any) => <div className="trace" key={trace.chunk}><span>{trace.chunk}</span><b>{trace.score}</b><Status value={trace.relevant ? "Relevant" : "Irrelevant"} /></div>)}<h4>Root Cause · {selected.confidence || "—"}% confidence</h4><ul>{(selected.evidence || ["See evaluation evidence."]).map((evidence: string) => <li key={evidence}>{evidence}</li>)}</ul><button className="primary full" onClick={() => { setSelected(null); navigate("evolution"); }}>Optimize This Run</button></div>}</Drawer>
  </div>;
}
function MetricGroup({ title, rows }: { title: string; rows: string[][] }) { return <section className="metric-group"><h3>{title}</h3>{rows.map(row => <div key={row[0]}><span>{row[0]}</span><strong>{row[1]}</strong></div>)}</section>; }
