import { useEffect, useState } from "react";
import { Check, Circle, Play, Sparkles } from "lucide-react";
import { getJson, postJson } from "../api";
import { Badge, Section, Status } from "../components/Primitives";

export function EvolutionPage({ data }: { data: any }) {
  const [run, setRun] = useState<any>(null); const [busy, setBusy] = useState(false); const evolution = data.optimization;
  useEffect(() => { if (!run || run.status === "completed") return; const timer = window.setInterval(async () => setRun(await getJson(`/api/experiments/${run.id}`)), 700); return () => window.clearInterval(timer); }, [run?.id, run?.status]);
  const start = async () => { setBusy(true); try { setRun(await postJson("/api/experiments/run")); } finally { setBusy(false); } };
  return <div className="page"><div className="page-title"><div><div className="eyebrow">Optimization Run · #{evolution.id}</div><h1>Evolution Lab</h1><p>Baseline v1.0 · Evaluation EVAL-0042 · 8 Bad Cases</p></div><button className="primary" onClick={start} disabled={busy || (run && run.status !== "completed")}><Play size={15} /> {busy ? "Starting…" : run && run.status !== "completed" ? "Experiment running" : "Run Experiments"}</button></div>
    <Section title="Agent Analysis Timeline" action={<Badge tone="accent"><Sparkles size={12} /> Structured agent</Badge>}><div className="timeline">{evolution.timeline.map((step: any) => <div key={step.action} className="timeline-item"><Check size={15} /><div><strong>{step.action}</strong><span>Result · {step.result}</span></div><Status value={step.status} /></div>)}</div></Section>
    <div className="two-column"><Section title="Agent Diagnosis"><div className="diagnosis"><div><span>Primary</span><strong>{evolution.diagnosis.primary}</strong><small>4 / 8 Bad Cases</small></div><div><span>Secondary</span><strong>{evolution.diagnosis.secondary}</strong><small>2 / 8 Bad Cases</small></div></div><p>{evolution.diagnosis.summary}</p><div className="other">{Object.entries(evolution.diagnosis.other).map(([name, value]) => <span key={name}>{name} <b>{value as any}</b></span>)}</div></Section><Section title="Sandbox Boundary"><p>Each candidate is a config snapshot evaluated independently. The active configuration is not modified.</p><Badge tone="neutral">Logical isolation · no containers</Badge></Section></div>
    <Section title="Candidate Configurations"><div className="candidate-cards">{evolution.candidates.map((candidate: any) => <article className={`candidate-card ${candidate.id === "B" ? "recommended" : ""}`} key={candidate.id}>{candidate.id === "B" && <Badge tone="good">Recommended historical result</Badge>}<span>Candidate {candidate.id}</span><h3>{candidate.strategy}</h3><dl>{Object.entries(candidate.settings).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value as any}</dd></div>)}</dl><p><b>Goal:</b> {candidate.goal}</p><small>{candidate.tradeoff}</small></article>)}</div></Section>
    <Experiment run={run} candidates={evolution.candidates} recommendation={evolution.recommendation} />
  </div>;
}
function Experiment({ run, candidates, recommendation }: { run: any; candidates: any[]; recommendation: any }) { const showingResult = !run || run.status === "completed"; return <><Section title="Sandbox Experiment"><div className="experiment-status">{run ? <><Status value={run.status} /><span>Replay #{run.id} · complete in about 6 seconds</span></> : <span>Historical experiment completed. Start a replay to visualize execution.</span>}</div><div className="progress-list">{(run?.candidates || candidates.map((candidate: any) => ({ ...candidate, completed_cases: 40, total_cases: 40 }))).map((candidate: any) => <div key={candidate.id}><div><strong>{candidate.name}</strong><span>{candidate.completed_cases} / {candidate.total_cases} Cases</span></div><div className="progress"><i style={{ width: `${candidate.completed_cases / candidate.total_cases * 100}%` }} /></div></div>)}</div></Section>{showingResult && <><Section title="Experiment Result"><table><thead><tr><th>Metric</th><th>Baseline</th>{candidates.map((candidate: any) => <th key={candidate.id} className={candidate.id === "B" ? "recommended-text" : ""}>Candidate {candidate.id}</th>)}</tr></thead><tbody>{[["Correctness", "78", "correctness"], ["Faithfulness", "91", "faithfulness"], ["Recall", "82", "recall"], ["P95 Latency", "3.6s", "p95_latency"], ["Overall", "72.4", "overall"]].map(([label, baseline, key]) => <tr key={label}><td>{label}</td><td>{baseline}</td>{candidates.map((candidate: any) => <td key={candidate.id} className={candidate.id === "B" ? "recommended-text" : ""}>{candidate.metrics[key]}{key === "p95_latency" ? "s" : ""}</td>)}</tr>)}</tbody></table></Section><Section title="SLA Gate"><div className="sla-gates">{candidates.map((candidate: any) => <div key={candidate.id}><h3>Candidate {candidate.id}</h3>{Object.entries(candidate.sla).map(([key, value]) => <p key={key}><span>{key}</span><Status value={value as string} /></p>)}</div>)}</div><div className="regression"><Circle size={18} fill="#1d8b68" color="#1d8b68" /><div><strong>40 / 40 Regression Completed</strong><span>Bad Cases Resolved {recommendation.bad_cases_resolved} · No New Regression · Unresolved {recommendation.unresolved}</span></div></div></Section></>}</> }
