import { useState } from "react";
import { errorMessage, postJson } from "../api";
import { Badge } from "../components/Primitives";
import type { Citation } from "../types";

export function ExperimentPage({ onOpenCitation }: { onOpenCitation: (citation: Citation) => void }) {
  const [question, setQuestion] = useState("B2 遥控器低电量时如何充电？"); const [result, setResult] = useState<any>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const ask = async () => { setLoading(true); setError(""); setResult(null); try { setResult(await postJson("/api/preview", { question })); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } };
  return <div className="page experiment-page"><div className="page-title"><div><h1>问答试验</h1><p>对同一机器人问题，查看基线版本与候选方案 B 的回答对照。</p></div></div><section className="panel experiment-query"><div className="section-head"><h2>按当前配置对比回答</h2></div><p className="notice">不上传原文件。提交问题后，相关知识片段可能发送至 DeepSeek。</p><label className="question-input"><span>问题</span><textarea aria-label="试验问题" maxLength={1000} value={question} onChange={event => setQuestion(event.target.value)} /></label><button className="primary" onClick={ask} disabled={loading || !question.trim()}>{loading ? "正在对比…" : "对比版本"}</button>{error && <p className="error-notice" role="alert">预览失败：{error}。请重试。</p>}</section><section className="experiment-pipelines" aria-label="对比 Pipeline"><article><Badge tone="neutral">Pipeline A</Badge><h2>基线版本</h2><p>使用当前基线配置，保留原始答案作为对照。</p></article><article><Badge tone="neutral">Pipeline B</Badge><h2>候选方案 B</h2><p>使用当前候选方案，展示同题回答与可追溯引用。</p></article></section><section className="experiment-results" aria-label="Pipeline 回答"><article><header><Badge tone="neutral">Pipeline A · {result?.baseline.version || "基线版本"}</Badge></header>{result ? <><p className="muted">本次问题：{result.question}</p><p>{result.baseline.answer}</p></> : <p className="muted">提交问题后显示 Pipeline A 的回答。</p>}</article><article><header><Badge tone="neutral">Pipeline B · {result?.candidate_b.version || "候选方案 B"}</Badge></header>{result ? <><p className="muted">{result.mode === "live" ? "服务回答" : "本地响应"} · 模型：{result.model ?? "未返回有效模型回答"} · 延迟：{result.latency_ms == null ? "未测量" : `${result.latency_ms} ms`}</p><p className="muted">处理说明：{result.fallback_reason || "无"}</p><p>{result.candidate_b.answer}</p>{result.candidate_b.evidence?.map((citation: Citation) => <button className="document-link" key={citation.chunk_id} onClick={() => onOpenCitation(citation)}>{citation.document} · P.{citation.page_start} · {citation.chunk_id} · {citation.score.toFixed(2)}</button>)}</> : <p className="muted">提交问题后显示 Pipeline B 的回答与可追溯引用。</p>}</article></section></div>;
}
