import { useState } from "react";
import { Send } from "lucide-react";
import { errorMessage, postJson } from "../api";
import { Badge } from "../components/Primitives";
import type { Citation } from "../types";

const pipelineOptions = [["v1.0", "Baseline · v1.0"], ["v1.1", "Candidate A · v1.1"], ["v1.2", "Candidate B · v1.2"], ["v1.3", "Candidate C · v1.3"]];

export function ExperimentPage({ onOpenCitation }: { onOpenCitation: (citation: Citation) => void }) {
  const [question, setQuestion] = useState(""); const [result, setResult] = useState<any>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [pipelineA, setPipelineA] = useState("v1.0"); const [pipelineB, setPipelineB] = useState("v1.2");
  const ask = async () => { setLoading(true); setError(""); setResult(null); try { setResult(await postJson("/api/preview", { question })); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } };
  return <div className="page experiment-page"><div className="page-title"><div><h1>问答试验</h1></div></div><section className="panel experiment-query"><label className="question-input"><textarea aria-label="试验问题" maxLength={1000} value={question} onChange={event => setQuestion(event.target.value)} /></label><div className="experiment-composer"><button className="primary" onClick={ask} disabled={loading || !question.trim()}>{loading ? "正在发送…" : <><Send size={15} />发送</>}</button></div>{error && <p className="error-notice" role="alert">预览失败：{error}。请重试。</p>}</section><section className="experiment-pipelines" aria-label="对比 Pipeline"><label className="pipeline-selector"><select aria-label="Pipeline A 演示配置" value={pipelineA} onChange={event => setPipelineA(event.target.value)}>{pipelineOptions.slice(0, 2).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="pipeline-selector"><select aria-label="Pipeline B 演示配置" value={pipelineB} onChange={event => setPipelineB(event.target.value)}>{pipelineOptions.slice(2).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></section><section className="experiment-results" aria-label="Pipeline 回答"><article className="experiment-answer-card"><header><Badge tone="neutral">Pipeline A · Baseline</Badge></header><div className="answer-scroll">{result ? <Answer content={result.baseline.answer} /> : <p className="muted">发送问题后显示 Pipeline A 的回答。</p>}</div></article><article className="experiment-answer-card"><header><Badge tone="neutral">Pipeline B · 候选方案 B</Badge></header><div className="answer-scroll">{result ? <><Answer content={result.candidate_b.answer} />{result.candidate_b.evidence?.length ? <div className="evidence-list"><span>检索证据</span>{result.candidate_b.evidence.map((citation: Citation) => <button className="document-link" key={citation.chunk_id} onClick={() => onOpenCitation(citation)}>{citation.document} · P.{citation.page_start} · {citation.chunk_id} · {citation.score.toFixed(2)}</button>)}</div> : null}</> : <p className="muted">发送问题后显示 Pipeline B 的回答。</p>}</div></article>{result && <><Parameters rows={[["版本", result.baseline.version], ["生成模型", "基线展示"], ["处理延迟", "未测量"], ["Top K", "—"], ["检索状态", "未运行独立检索"]]} /><Parameters rows={[["版本", result.candidate_b.version], ["回答模式", result.mode === "live" ? "服务回答" : "本地响应"], ["生成模型", result.model ?? "未返回有效模型回答"], ["处理延迟", result.latency_ms == null ? "未测量" : `${result.latency_ms} ms`], ["Top K", "4"], ["检索", "BGE + FAISS"], ["处理说明", result.fallback_reason || "无"]]} /></>}</section></div>;
}

function Answer({ content }: { content: string }) {
  const lines = content.replace(/(\d+\.\s+\*\*)/g, "\n$1").replace(/\s+-\s+/g, "\n- ").split(/\n+/).filter(Boolean);
  return <div className="answer-content">{lines.map((line, index) => <p key={index}>{line.split(/(\*\*[^*]+\*\*)/g).map((part, partIndex) => part.startsWith("**") ? <strong key={partIndex}>{part.slice(2, -2)}</strong> : part)}</p>)}</div>;
}

function Parameters({ rows }: { rows: string[][] }) { return <dl className="run-parameters">{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>; }
