import { useState } from "react";
import { errorMessage, postJson } from "../api";
import { Badge, Metric, Section, Status } from "../components/Primitives";

export function GovernancePage({ data }: { data: any }) {
  const [items, setItems] = useState<any[]>(data.dataset || []); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const candidates = items.filter(item => item.stage === "candidate"); const golden = items.filter(item => item.stage === "golden");
  const update = (item: any) => setItems(current => current.map(row => row.id === item.id ? item : row));
  const run = async (id: string, action: "probe" | "qc") => { setBusy(true); setError(""); try { const result: any = await postJson(`/api/governance/questions/${id}/${action}`); update({ ...items.find(item => item.id === id), ...(action === "probe" ? { probe_status: result.status } : { qc_status: result.status }) }); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const approve = async (id: string) => { setBusy(true); setError(""); try { update(await postJson(`/api/governance/questions/${id}/review`, { decision: "approved" })); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const generate = async () => { setBusy(true); setError(""); try { const result: any = await postJson("/api/governance/generate-mini"); setItems(current => [...current, ...result.candidates]); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  return <div className="page"><div className="page-title"><div><h1>测试集治理</h1><p>Candidate → Probe ≥90 → QC ≥85 → Human Review → Golden Snapshot；历史题目仅为待审核候选。</p></div><button className="secondary" disabled={busy} onClick={() => void generate()}>{busy ? "处理中…" : "生成 Mini 8 / 4 / 8"}</button></div>{error && <p className="error-notice" role="alert">{error}</p>}<div className="metrics-grid four"><Metric label="候选题" value={String(candidates.length)} /><Metric label="Positive" value={String(items.filter(item => item.test_category === "positive").length)} /><Metric label="Ablation" value={String(items.filter(item => item.test_category === "ablation").length)} /><Metric label="已批准 Golden" value={String(golden.length)} /></div><Section title="治理流程"><div className="pipeline">{["Candidate", "Hard Validation", "Probe", "QC", "Human Review", "Golden Snapshot"].map(label => <div className="pipeline-node" key={label}><span>{label}</span><strong>{label === "Golden Snapshot" ? golden.length : "受控"}</strong></div>)}</div></Section><Section title="Golden Candidate 与人工审核"><p className="muted">系统不会自动批准 Candidate；Probe 或 QC 失败时需修订后重新治理。</p><QuestionTable rows={candidates} busy={busy} onProbe={id => run(id, "probe")} onQc={id => run(id, "qc")} onApprove={approve} /></Section><Section title="Approved Golden Snapshot"><QuestionTable rows={golden} busy={busy} /></Section></div>;
}

function QuestionTable({ rows, busy, onProbe, onQc, onApprove }: { rows: any[]; busy: boolean; onProbe?: (id: string) => void; onQc?: (id: string) => void; onApprove?: (id: string) => void }) {
  return <div className="table-scroll"><table><thead><tr><th>ID</th><th>类型</th><th>问题</th><th>审核</th><th>Probe / QC</th><th>操作</th></tr></thead><tbody>{rows.map(row => { const ready = row.probe_status === "probe_passed" && row.qc_status === "qc_passed"; return <tr key={row.id}><td>{row.id}</td><td><Badge tone={row.test_category === "negative" ? "warning" : "neutral"}>{row.test_category}</Badge></td><td>{row.question}</td><td><Status value={row.review_status || "pending"} /></td><td><Status value={row.probe_status || "not_run"} /> {row.qc_status && <Status value={row.qc_status} />}</td><td>{onProbe && <button className="secondary" disabled={busy} onClick={() => onProbe(row.id)}>Probe</button>} {onQc && <button className="secondary" disabled={busy || row.probe_status !== "probe_passed"} onClick={() => onQc(row.id)}>QC</button>} {onApprove && <button className="primary" disabled={busy || !ready} onClick={() => onApprove(row.id)}>批准为 Golden</button>}</td></tr>; })}{!rows.length && <tr><td colSpan={6} className="empty-state">暂无符合条件的真实数据。</td></tr>}</tbody></table></div>;
}
