import { useState } from "react";
import { FileText, Search } from "lucide-react";
import { Drawer } from "../components/Dialog";
import { Badge, Section, Status } from "../components/Primitives";

export function KnowledgePage({ data }: { data: any }) {
  const [tab, setTab] = useState("knowledge"); const [selected, setSelected] = useState<any>(null); const [query, setQuery] = useState("");
  const documents = data.documents.filter((item: any) => item.name.toLowerCase().includes(query.toLowerCase()));
  return <div className="page"><div className="page-title"><div><h1>Knowledge & Dataset</h1><p>Evidence foundations for reproducible evaluation.</p></div></div><div className="tabs"><button className={tab === "knowledge" ? "selected" : ""} onClick={() => setTab("knowledge")}>Knowledge Base</button><button className={tab === "dataset" ? "selected" : ""} onClick={() => setTab("dataset")}>Golden Dataset</button></div>
    {tab === "knowledge" ? <><div className="metrics-grid four"><div className="metric"><span>Documents</span><strong>12</strong></div><div className="metric"><span>Chunks</span><strong>438</strong></div><div className="metric"><span>Index</span><strong>Indexed</strong></div><div className="metric"><span>Last Sync</span><strong>Today 14:32</strong></div></div><Section title="Source Documents" action={<label className="search"><Search size={15} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search documents" /></label>}><table><thead><tr><th>Document</th><th>Category</th><th>Pages</th><th>Chunks</th><th>Index Status</th><th>Updated</th></tr></thead><tbody>{documents.map((doc: any) => <tr key={doc.id} onClick={() => setSelected(doc)}><td><FileText size={15} /> {doc.name}</td><td>{doc.category}</td><td>{doc.pages}</td><td>{doc.chunks}</td><td><Status value={doc.status} /></td><td>{doc.updated_at}</td></tr>)}</tbody></table></Section></> : <Dataset rows={data.dataset} />}
    <Drawer open={!!selected} onOpenChange={() => setSelected(null)} title={selected?.name || "Document Metadata"}>{selected && <div className="drawer-body"><Badge tone="accent">{selected.category}</Badge><dl><dt>Parser</dt><dd>{selected.parser}</dd><dt>Chunk Strategy</dt><dd>{selected.chunk_strategy}</dd><dt>Chunk Count</dt><dd>{selected.chunks}</dd><dt>Embedding Status</dt><dd><Status value={selected.status} /></dd></dl><h3>Sample chunks</h3>{selected.samples.map((sample: string, index: number) => <blockquote key={sample}><span>Chunk #{index + 1}</span>{sample}</blockquote>)}</div>}</Drawer>
  </div>;
}

function Dataset({ rows }: { rows: any[] }) { return <><div className="dataset-flow"><span>Knowledge Base</span><b>→</b><span>AI Generate</span><b>→</b><span>Human Review</span><b>→</b><strong>Golden Dataset v1.3</strong></div><div className="metrics-grid four"><Metric label="Total" value="40" /><Metric label="Positive" value="22" /><Metric label="Ablation" value="10" /><Metric label="Negative" value="8" /></div><Section title="Golden Dataset" action={<Badge tone="good">40 Reviewed</Badge>}><table><thead><tr><th>ID</th><th>Type</th><th>Question</th><th>Expected Answer</th><th>Source</th><th>Review</th></tr></thead><tbody>{rows.map((row: any) => <tr key={row.id}><td>{row.id}</td><td><Badge tone={row.type === "Negative" ? "warning" : "neutral"}>{row.type}</Badge></td><td>{row.question}</td><td className="truncate">{row.expected_answer}</td><td>{row.source}</td><td><Status value={row.review_status} /></td></tr>)}</tbody></table></Section></> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
