import { useEffect, useState } from "react";
import { BookOpen, Database, FileText, Search } from "lucide-react";
import { Drawer } from "../components/Dialog";
import { Badge, Section, Status } from "../components/Primitives";
import { displayText } from "../display";

export function KnowledgePage({ data, openedDocumentName, onOpenedDocument }: { data: any; openedDocumentName?: string; onOpenedDocument?: () => void }) {
  const [tab, setTab] = useState("knowledge");
  const [selected, setSelected] = useState<any>(null);
  const [query, setQuery] = useState("");
  const documents = data.documents.filter((item: any) => item.name.toLowerCase().includes(query.toLowerCase()));
  const chunkCount = data.documents.reduce((total: number, item: any) => total + item.chunks, 0);
  useEffect(() => { if (!openedDocumentName) return; const document = data.documents.find((item: any) => item.name === openedDocumentName); if (document) setSelected(document); onOpenedDocument?.(); }, [data.documents, onOpenedDocument, openedDocumentName]);
  return <div className="page"><div className="page-title"><div><h1>知识与数据集</h1></div></div><div className="tabs"><button className={tab === "knowledge" ? "selected" : ""} onClick={() => setTab("knowledge")}><BookOpen size={15} />知识库</button><button className={tab === "dataset" ? "selected" : ""} onClick={() => setTab("dataset")}><Database size={15} />黄金数据集</button></div>
    {tab === "knowledge" ? <><div className="metrics-grid four"><Metric label="文档数" value={String(data.documents.length)} /><Metric label="分块数" value={String(chunkCount)} /><Metric label="索引状态" value="已索引" /><Metric label="资料来源" value="官方 PDF" /></div><Section title="源文档" action={<label className="search"><Search size={15} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索文档" /></label>}><div className="table-scroll" role="region" aria-label="知识数据表" tabIndex={0}><table><thead><tr><th>文档</th><th>分类</th><th>页数</th><th>分块数</th><th>索引状态</th><th>更新时间</th></tr></thead><tbody>{documents.length === 0 && <tr><td colSpan={6} className="empty-state">未找到匹配文档，请更换关键词。</td></tr>}{documents.map((doc: any) => <tr key={doc.id}><td><button className="text-button detail-button" onClick={() => setSelected(doc)}><FileText size={15} />{doc.name}</button></td><td>{doc.category}</td><td>{doc.pages}</td><td>{doc.chunks}</td><td><Status value={doc.status} /></td><td>{displayText(doc.updated_at)}</td></tr>)}</tbody></table></div></Section></> : <Dataset rows={data.dataset} />}
    <Drawer open={!!selected} onOpenChange={() => setSelected(null)} title={selected?.name || "文档元数据"}>{selected && <div className="drawer-body"><Badge tone="accent">{selected.category}</Badge><dl><dt>解析器</dt><dd>{displayText(selected.parser)}</dd><dt>分块策略</dt><dd>{displayText(selected.chunk_strategy)}</dd><dt>分块数量</dt><dd>{selected.chunks}</dd><dt>嵌入状态</dt><dd><Status value={selected.status} /></dd></dl><a className="secondary" href={selected.pdf_url} target="_blank" rel="noreferrer">打开 PDF</a><article className="document-reader" aria-label="文档在线浏览"><header><span>已核验片段</span><p>原始 PDF · 共 {selected.pages} 页</p></header>{(selected.content || selected.samples).map((section: string, index: number) => { const [title, ...body] = section.split("\n"); return <section key={`${title}-${index}`}><h3>{title}</h3><p>{body.join("\n") || title}</p></section>; })}</article></div>}</Drawer>
  </div>;
}

function Dataset({ rows }: { rows: any[] }) { const reviewed = rows.filter(row => row.review_status === "Reviewed").length; return <><div className="metrics-grid four"><Metric label="总数" value={String(rows.length)} /><Metric label="已复核" value={String(reviewed)} /><Metric label="官方来源" value={String(rows.filter(row => row.source).length)} /><Metric label="资料范围" value="机器人 PDF" /></div><Section title="机器人评测集" action={<Badge tone="good">{reviewed} 条已审核</Badge>}><div className="table-scroll" role="region" aria-label="知识数据表" tabIndex={0}><table><thead><tr><th>ID</th><th>类型</th><th>问题</th><th>预期回答</th><th>来源</th><th>审核状态</th></tr></thead><tbody>{rows.map((row: any) => <tr key={row.id}><td>{row.id}</td><td><Badge tone={row.type === "Negative" ? "warning" : "neutral"}>{displayText(row.type)}</Badge></td><td>{row.question}</td><td className="truncate">{row.expected_answer}</td><td>{displayText(row.source)}</td><td><Status value={row.review_status} /></td></tr>)}</tbody></table></div></Section></> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
