import { useState } from "react";
import { errorMessage, getJson, postJson } from "../api";
import { Section, Status } from "../components/Primitives";
import { AssistantPage } from "./AssistantPage";
import { ExperimentPage } from "./ExperimentPage";
import type { Citation } from "../types";
import { useOperation } from "../operation";

export function VerificationPage({ data, onOpenCitation, onOpenDocument }: { data: any; onOpenCitation: (citation: Citation) => void; onOpenDocument: (name: string) => void }) {
  const operation = useOperation();
  const [tab, setTab] = useState<"qa" | "compare" | "monitoring">("qa"), [busy, setBusy] = useState(false), [error, setError] = useState(""), [monitoring, setMonitoring] = useState<any>(data.monitoring || {});
  const refresh = async () => setMonitoring(await getJson("/api/monitoring"));
  const assess = async (event: any, bad_case: boolean, severity: "ordinary" | "critical") => { setBusy(true); setError(""); try { await operation.run("保存人工监控判定", () => postJson(`/api/monitoring/events/${event.id}/assessment`, { bad_case, severity })); await refresh(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const confirm = async (trigger: any) => { setBusy(true); setError(""); try { await operation.run("确认 Optimization Trigger", () => postJson(`/api/monitoring/triggers/${trigger.id}/confirm`, { decision: "approved" })); await refresh(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  return <div className="page verification-page"><div className="page-title"><div><h1>问答验证</h1><p>真实 Production 问答、同题优化前后对比与人工生产监控判定。</p></div></div><div className="tabs"><button aria-pressed={tab === "qa"} className={tab === "qa" ? "selected" : ""} onClick={() => setTab("qa")}>生产问答</button><button aria-pressed={tab === "compare"} className={tab === "compare" ? "selected" : ""} onClick={() => setTab("compare")}>优化前后对比</button><button aria-pressed={tab === "monitoring"} className={tab === "monitoring" ? "selected" : ""} onClick={() => setTab("monitoring")}>生产监控</button></div>{tab === "qa" && <AssistantPage productionVersion={data.workspace?.active_version} badCases={data.badCases || []} onOpenBadCase={() => {}} onOpenCitation={onOpenCitation} onOpenDocument={onOpenDocument} />}{tab === "compare" && <ExperimentPage onOpenCitation={onOpenCitation} />}{tab === "monitoring" && <Section title="生产监控 / Human Confirm">{error && <p className="error-notice" role="alert">{error}</p>}<p className="muted">人工判定后立即刷新事件与 Trigger；不会自动调参或发布。</p><div className="run-list">{(monitoring.events || []).map((event: any) => <div key={event.id}><strong>{event.question}</strong><span>{event.determinable ? (event.bad_case ? "Bad Case" : "已判定正常") : "待人工判定"}</span>{!event.determinable && <span><button className="secondary" disabled={busy} onClick={() => void assess(event, false, "ordinary")}>标记正常</button> <button className="secondary" disabled={busy} onClick={() => void assess(event, true, "ordinary")}>标记 Bad Case</button> <button className="secondary" disabled={busy} onClick={() => void assess(event, true, "critical")}>标记 Safety Critical</button></span>}</div>)}{!(monitoring.events || []).length && <p className="muted">暂无可判定的真实问答记录。</p>}</div><div className="run-list">{(monitoring.triggers || []).map((trigger: any) => <div key={trigger.id}><strong>{trigger.reason}</strong><Status value={trigger.status} />{trigger.status === "pending_human_confirm" && <button className="secondary" disabled={busy} onClick={() => void confirm(trigger)}>Human Confirm</button>}</div>)}</div></Section>}</div>;
}
