import { useState } from "react";
import { errorMessage, postJson } from "../api";
import { Section, Status } from "../components/Primitives";
import { AssistantPage } from "./AssistantPage";
import { ExperimentPage } from "./ExperimentPage";
import type { Citation } from "../types";

export function VerificationPage({ data, onOpenCitation, onOpenDocument }: { data: any; onOpenCitation: (citation: Citation) => void; onOpenDocument: (name: string) => void }) {
  const [tab, setTab] = useState<"qa" | "compare" | "monitoring">("qa"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const monitoring = data.monitoring || {};
  const assess = async (event: any, severity: "ordinary" | "critical") => { setBusy(true); setError(""); try { await postJson(`/api/monitoring/events/${event.id}/assessment`, { bad_case: true, severity }); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const confirm = async (trigger: any) => { setBusy(true); setError(""); try { await postJson(`/api/monitoring/triggers/${trigger.id}/confirm`, { decision: "approved" }); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  return <div className="page verification-page"><div className="page-title"><div><h1>问答验证</h1><p>真实 Production 问答、同题 Before / After 比较与人工 Monitoring 判定。</p></div></div><div className="tabs"><button className={tab === "qa" ? "selected" : ""} onClick={() => setTab("qa")}>Production Q&A</button><button className={tab === "compare" ? "selected" : ""} onClick={() => setTab("compare")}>Before / After</button><button className={tab === "monitoring" ? "selected" : ""} onClick={() => setTab("monitoring")}>Monitoring</button></div>{tab === "qa" && <AssistantPage productionVersion={data.workspace?.active_version} badCases={data.badCases || []} onOpenBadCase={() => {}} onOpenCitation={onOpenCitation} onOpenDocument={onOpenDocument} />}{tab === "compare" && <ExperimentPage onOpenCitation={onOpenCitation} />}{tab === "monitoring" && <Section title="Monitoring / Human Confirm">{error && <p className="error-notice" role="alert">{error}</p>}<p className="muted">只有人工确认的 Bad Case 会触发待确认 Optimization Trigger；不会自动调参或发布。</p><div className="run-list">{(monitoring.events || []).map((event: any) => <div key={event.id}><strong>{event.question}</strong><span>{event.determinable ? (event.bad_case ? "Bad Case" : "已判定") : "待人工判定"}</span>{!event.determinable && <span><button className="secondary" disabled={busy} onClick={() => void assess(event, "ordinary")}>标记 Bad Case</button> <button className="secondary" disabled={busy} onClick={() => void assess(event, "critical")}>标记 Safety Critical</button></span>}</div>)}{!(monitoring.events || []).length && <p className="muted">暂无可判定的真实问答记录。</p>}</div><div className="run-list">{(monitoring.triggers || []).map((trigger: any) => <div key={trigger.id}><strong>{trigger.reason}</strong><Status value={trigger.status} />{trigger.status === "pending_human_confirm" && <button className="secondary" disabled={busy} onClick={() => void confirm(trigger)}>Human Confirm</button>}</div>)}</div></Section>}</div>;
}
