import { useState } from "react";
import { errorMessage, getJson, postJson } from "../api";
import { Section, Status } from "../components/Primitives";
import { AssistantPage } from "./AssistantPage";
import { ExperimentPage } from "./ExperimentPage";
import type { Citation } from "../types";
import { useOperation } from "../operation";

export function VerificationPage({ data, onOpenCitation, onOpenDocument }: { data: any; onOpenCitation: (citation: Citation) => void; onOpenDocument: (name: string) => void }) {
  const operation = useOperation();
  const [tab, setTab] = useState<"qa" | "compare" | "monitoring">("qa"), [busy, setBusy] = useState(false), [error, setError] = useState(""), [monitoring, setMonitoring] = useState<any>(data.monitoring || {});
  const refresh = async () => setMonitoring(await getJson("/api/monitoring"));
  const assess = async (event: any, bad_case: boolean, severity: "ordinary" | "critical") => { setBusy(true); setError(""); try { await operation.run("保存人工监控判定", () => postJson(`/api/monitoring/events/${event.id}/assessment`, { bad_case, severity })); await refresh(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const confirm = async (trigger: any) => { setBusy(true); setError(""); try { await operation.run("确认 Optimization Trigger", () => postJson(`/api/monitoring/triggers/${trigger.id}/confirm`, { decision: "approved" })); await refresh(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const released = data.versions?.find((version: any) => version.status === "active")?.provenance === "published";
  return <div className="page verification-page"><div className="page-title"><div><h1>QA Playground</h1><p>验证当前配置、比较同题 Before / After，并查看轻量 Monitoring。</p></div></div><div className="tabs"><button aria-pressed={tab === "qa"} className={tab === "qa" ? "selected" : ""} onClick={() => setTab("qa")}>QA Playground</button><button aria-pressed={tab === "compare"} className={tab === "compare" ? "selected" : ""} onClick={() => setTab("compare")}>Before / After</button><button aria-pressed={tab === "monitoring"} className={tab === "monitoring" ? "selected" : ""} onClick={() => setTab("monitoring")}>Monitoring</button></div>{tab === "qa" && <AssistantPage productionVersion={data.workspace?.active_version} isReleased={released} badCases={data.badCases || []} onOpenBadCase={() => {}} onOpenCitation={onOpenCitation} onOpenDocument={onOpenDocument} />}{tab === "compare" && <ExperimentPage data={data} onOpenCitation={onOpenCitation} />}{tab === "monitoring" && <Section title="Monitoring · Human Confirm"><p className="muted">Current Production：{data.workspace?.active_version || "未发布"} · 最近 QA {monitoring.events?.length || 0} · Pending Trigger {(monitoring.triggers || []).filter((item: any) => item.status === "pending_human_confirm").length}</p>{error && <p className="error-notice" role="alert">{error}</p>}<p className="muted">Trigger → Human Confirm → Optimization Agent；不会自动调参或发布。</p><div className="run-list">{(monitoring.events || []).map((event: any) => <div key={event.id}><strong>{event.question}</strong><span>{event.determinable ? (event.bad_case ? "Bad Case" : "已判定正常") : "待人工判定"}</span>{!event.determinable && <span><button className="secondary" disabled={busy} onClick={() => void assess(event, false, "ordinary")}>标记正常</button> <button className="secondary" disabled={busy} onClick={() => void assess(event, true, "ordinary")}>标记 Bad Case</button> <button className="secondary" disabled={busy} onClick={() => void assess(event, true, "critical")}>标记安全问题</button></span>}</div>)}{!(monitoring.events || []).length && <p className="muted">暂无可判定的真实问答记录。</p>}</div><div className="run-list">{(monitoring.triggers || []).map((trigger: any) => <div key={trigger.id}><strong>{trigger.reason}</strong><Status value={trigger.status} />{trigger.status === "pending_human_confirm" && <button className="secondary" disabled={busy} onClick={() => void confirm(trigger)}>人工确认</button>}</div>)}</div></Section>}</div>;
}
