import { useState } from "react";
import { errorMessage, postJson } from "../api";
import { Section, Status } from "../components/Primitives";

export function VersionsPage({ data }: { data: any }) {
  const [versions, setVersions] = useState(data.versions || []); const [candidates, setCandidates] = useState<any[]>(data.optimization?.candidates || []); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const rollback = async (version: any) => { setBusy(true); setError(""); try { const active: any = await postJson(`/api/versions/${version.id}/rollback`, { decision: "approved" }); setVersions((current: any[]) => current.map(item => ({ ...item, status: item.id === active.id ? "active" : item.status === "active" ? "archived" : item.status }))); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const release = async (candidate: any, step: "approval" | "release-approval" | "publish") => { setBusy(true); setError(""); try { const result: any = await postJson(`/api/candidates/${candidate.id}/${step}`, { decision: "approved" }); if (step === "publish") setVersions((current: any[]) => [result, ...current]); setCandidates((current: any[]) => current.map(item => item.id === candidate.id ? { ...item, approval_updated: true } : item)); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  return <div className="page"><div className="page-title"><div><h1>版本与发布</h1><p>Candidate 只能经 Sandbox、人工 Candidate Approval、Release Approval 后发布；AI 不可自动上线。</p></div></div>{error && <p className="error-notice" role="alert">{error}</p>}<Section title="待发布 Candidate"><div className="run-list">{candidates.map(candidate => <div key={candidate.id}><strong>{candidate.id}</strong><span>{candidate.result?.qualification?.qualified ? "已通过 Gate 与 Regression" : "未满足发布条件"}</span><span><button className="secondary" disabled={busy || !candidate.result?.qualification?.qualified} onClick={() => void release(candidate, "approval")}>Candidate Approval</button> <button className="secondary" disabled={busy || !candidate.result?.qualification?.qualified} onClick={() => void release(candidate, "release-approval")}>Release Approval</button> <button className="primary" disabled={busy || !candidate.result?.qualification?.qualified} onClick={() => void release(candidate, "publish")}>发布</button></span></div>)}{!candidates.length && <p className="muted">暂无可进入发布流程的真实 Candidate。</p>}</div></Section><Section title="Production Versions"><div className="table-scroll"><table><thead><tr><th>版本</th><th>配置</th><th>评测</th><th>状态</th><th></th></tr></thead><tbody>{versions.map((version: any) => <tr key={version.id}><td>{version.id}</td><td>CandidateK {version.config?.candidate_k ?? "—"} · TopK {version.config?.top_k ?? "—"} · Hybrid {String(version.config?.hybrid_search ?? "—")}</td><td>{version.evaluation_run_id || "未运行"}</td><td><Status value={version.status} /></td><td>{version.status !== "active" && <button className="secondary" disabled={busy} onClick={() => void rollback(version)}>回滚至此版本</button>}</td></tr>)}{!versions.length && <tr><td colSpan={5} className="empty-state">暂无 Production Version。</td></tr>}</tbody></table></div></Section><Section title="版本快照"><div className="run-list">{versions.map((version: any) => <div key={version.id}><strong>{version.id}</strong><span>模型 {version.snapshot?.model_version || "未运行"} · Golden {version.snapshot?.dataset_snapshot_version || "未运行"}</span><small>Gate {version.snapshot?.hard_gate_results?.passed_count ?? "—"} / {version.snapshot?.hard_gate_results?.total ?? "—"} · Regression {version.snapshot?.regression?.status || "未运行"} · 发布人 {version.snapshot?.human_release?.actor || "未运行"}</small></div>)}</div></Section></div>;
}
