import { useState } from "react";
import { errorMessage, postJson } from "../api";
import { Section, Status } from "../components/Primitives";

export function VersionsPage({ data }: { data: any }) {
  const [versions, setVersions] = useState(data.versions || []); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const rollback = async (version: any) => { setBusy(true); setError(""); try { const active: any = await postJson(`/api/versions/${version.id}/rollback`, { decision: "approved" }); setVersions((current: any[]) => current.map(item => ({ ...item, status: item.id === active.id ? "active" : item.status === "active" ? "archived" : item.status }))); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  return <div className="page"><div className="page-title"><div><h1>版本管理</h1><p>Experiment 与 Production 分离；发布需通过 Candidate Approval、Release Approval、11/11 Gate 与 Regression。</p></div></div>{error && <p className="error-notice" role="alert">{error}</p>}<Section title="Production Versions"><div className="table-scroll"><table><thead><tr><th>版本</th><th>配置</th><th>评测</th><th>状态</th><th></th></tr></thead><tbody>{versions.map((version: any) => <tr key={version.id}><td>{version.id}</td><td>CandidateK {version.config?.candidate_k ?? "—"} · TopK {version.config?.top_k ?? "—"} · Hybrid {String(version.config?.hybrid_search ?? "—")}</td><td>{version.evaluation_run_id || "Not Run"}</td><td><Status value={version.status} /></td><td>{version.status !== "active" && <button className="secondary" disabled={busy} onClick={() => void rollback(version)}>回滚至此版本</button>}</td></tr>)}{!versions.length && <tr><td colSpan={5} className="empty-state">暂无 Production Version。</td></tr>}</tbody></table></div></Section><Section title="Version Snapshot"><div className="run-list">{versions.map((version: any) => <div key={version.id}><strong>{version.id}</strong><span>Model {version.snapshot?.model_version || "Not Run"} · Dataset {version.snapshot?.dataset_snapshot_version || "Not Run"}</span><small>Gate {version.snapshot?.hard_gate_results?.passed_count ?? "—"} / {version.snapshot?.hard_gate_results?.total ?? "—"} · Regression {version.snapshot?.regression?.status || "Not Run"} · Release {version.snapshot?.human_release?.actor || "Not Run"}</small></div>)}</div></Section><Section title="Evolution Trend"><p className="muted">暂无足够版本数据，无法生成真实趋势。</p></Section></div>;
}
